### ISSUE TITLE
Weapons dont show up on the Workbenches

### ISSUE THREAD

**Issue by BigEvil4711** [MidnightsFX/Valheim_Armory#1]
If you use Mods that add Weapons with Same Names the Weapons dont Show up in the Workbenches.
I could only Spawn them with the Console or build them in Debugmode.

The Items where the Chitin Sword and the Royal Atgeir rest of the Items works without any Problem.

**Comment by MidnightsFX** [comment]
Hey! I have an update that should address this coming out, but it will be a relatively big change. Should fix all of the naming conflict issues.

**Comment by MidnightsFX** [comment]
Alrighty 1.0.0 is out and that should include changes to the names and recipes that should help prevent conflicts.

If you are still having conflicts lets take a look at what mods are also adding those items and I'll see what I can improve compatibility wise.
