### ISSUE TITLE
Incorrect recipe

### ISSUE THREAD

**Issue by smoothuk** [MidnightsFX/Valheim_Armory#10]
It appears that the crossbow "Moder's Dream" has the same forge recipe as the Bronze Crossbow.   Also using the wrong description?

Edit: The config recipe seems to be missing too.

![oops](https://github.com/MidnightsFX/Valheim_Armory/assets/59454941/0683ddcd-a1c6-4fed-8a6b-3958247e49e0)

**Comment by MidnightsFX** [comment]
Ahh drat I thought I had fixed that already, I'll get an update out with the fix tonight.

**Comment by MidnightsFX** [comment]
Fixed in 1.3.4
