### ISSUE TITLE
Moders AOE & Cool downs maybe?

### ISSUE THREAD

**Issue by Ashodinn** [MidnightsFX/Valheim_Armory#12]
Not that its a HUGE deal, but is it really intended for the new moder's AOE attack, to be able to clear an infested mine in a few seconds.  Because the skybox is shaped as a small square stacked, the Moder's attack covers the whole area, and kills everything inside it after a few casts... A bit op IMO.  I kind of feel like these boss weapons, should have a cooldown of like 60 seconds on their big attacks.  Or maybe add  an optional config for admins who run these weapons along side EPICmmo.  An optional 60/90/120 second cool down on the big attacks, or maybe also make them a "secondary" attack that has a cooldown, and give them a smaller primary attack that doesn't?  just thoughts.

SORRY WRONG MOD CANT FIGURE OUT HOW TO DELETE THIS

**Comment by MidnightsFX** [comment]
I was really confused reading this because all of my moders weapons are single target. Then I read to the end :)

No worries! I'll get the issue closed for you.
