### ISSUE TITLE
Suggestion: More weapons configurations

### ISSUE THREAD

**Issue by jimkimjat** [MidnightsFX/Valheim_Armory#13]
I was changing values for weapons using aedenthorn's Custom Weapons Stats mods. I noticed Valheim Armory does not have values like attackForce (weapon knockback) and deflectionForce (shield block knockback). I tried generating the json file for Valheim Armory weapons, but command says it couldn't find anything with the name (EikthyrsAtgeir). I am guessing aedenthorn's mod doesn't support custom weapons or I may have inserted the wrong prefab name.

Is it possible to include more configuration values for Valheim Armory? I find weapons like maces knock enemies too far away.

**Comment by MidnightsFX** [comment]
Yes! It is definitely possible, I can add these values as configurable in potentially the next update.

As for the prefab name if you want to use aedenthorns the prefab names are all defined in the items class, here is the [antler atgeir ](https://github.com/MidnightsFX/Valheim_Armory/blob/59dba3afc98c63142357748d45122ebe7cc19c91/ValheimArmory/ValheimArmoryItems.cs#LL855C38-L855C38)

**Comment by jimkimjat** [comment]
That worked perfect! Thank you very much!

**Comment by MidnightsFX** [comment]
Attack force will be added to the configs for all weapons, and deflection force will be added for all shields in the next update!

**Comment by MidnightsFX** [comment]
The release for this is finally out! 1.5.0 which provides the requested configs.
