### ISSUE TITLE
Another config suggestion- Crafting stations support

### ISSUE THREAD

**Issue by smoothuk** [MidnightsFX/Valheim_Armory#14]
If possible, support for crafting stations from other mods would be nice.  Example- crafting ValheimArmory arrows on the Fletcher Table (FletcherTable_TW) from Therzie's Warfare mod.  Cheers.

**Comment by MidnightsFX** [comment]
I can look into this, but right now that would require that this mod depends on other mods- as it would need those assets loaded before loading the VA weapons in order to reference those crafting pieces.

**Comment by MidnightsFX** [comment]
I've looked into this more and the only way I can safely allow using other crafting stations is forcing this mod to load after the other mods, aka making this mod dependent on others- and I don't want to add a lot of dependencies like that.

I can look at adding an optional compatibility layer which would provide some of this kind of functionality. But that is a much larger scope for currently very minimal gain. As of right now I don't have any plans to do that. But I will mention if that changes and I end up adding support for interfacing with other mods seamlessly.

**Comment by MidnightsFX** [comment]
Requested again, so I'll look into this for a future feature.

**Comment by MidnightsFX** [comment]
I've got some changes to this that will support this in an upcoming release 1.5.8, that should be out today or tomorrow.
