### ISSUE TITLE
A possible bug with sledgehammers.

### ISSUE THREAD

**Issue by LunaEversor** [MidnightsFX/Valheim_Armory#16]
I'm not really sure if this is a bug, or if it was intended. The sledgehammers seem to have no impact sound when striking the ground. Both the Sky Shatter and Elders Rock are affected.

**Comment by MidnightsFX** [comment]
Interesting! I think this was an issue on an older version of the mod since I had not properly mocked the soundfiles. I'll verify that's not the case anymore.

Which version are you running out of curiosity?

**Comment by MidnightsFX** [comment]
Looking into this next, it looks like the sound I was mocking for this has changed recently and thats causing the missing audio.

**Comment by LunaEversor** [comment]
Sorry for the late reply, I was using the latest version at the time. I'm assuming it was the last game update that caused it. I noticed it with WeaponAdditions by blacks7ar later on that night, although I had forgotten to report it to them.

**Comment by MidnightsFX** [comment]
Ok, got this verified, however I need to get an updated gamerip to fix the mockname.
That might take a little bit as I'm not an expert and waiting on others tooling updates for this.

I suspect that I'll have a fix available for this in the next week or two. It will break backwards compatibility for that sound, and there are likely other small changes like that. I'll be sure to mention in the notes as I find fix.

This won't cause game issues, just sadly missing audio for the moment :(

**Comment by MidnightsFX** [comment]
This should be fixed in the next release
