### ISSUE TITLE
Add new Elder boss weapons

### ISSUE THREAD

**Issue by MidnightsFX** [MidnightsFX/Valheim_Armory#17]
* Elders sword - rocky blade with a vine wrapping one side, growing down around the handle.
* Elders 1H mace - similar to Elders rock, smaller.

[similar sword concept](https://cdn.discordapp.com/attachments/1164392384545702058/1167925222217875576/root-sword-2.jpg?ex=654fe61f&is=653d711f&hm=c8e9da59461d5b676fb5fa7048b398f2a441ef8d6655954036fd32654db8ac26&)

**Comment by RaptorDread** [comment]
Elder 1H mace - "Elder" boss weapon idea using the handle of the 1-handed bronze mace, joining it with the Greydwar Brute weapon, with the purple cloth and the small stone on the handle of the Elder Hammer 2H mace from the Valheim Armory mod.

[concept](https://cdn.discordapp.com/attachments/1164392384545702058/1168344203475025950/Elder-Mace-1H.jpg?ex=65516c54&is=653ef754&hm=403eabe883be7507b997ca4403e46083b98a3c46bcc77fc33ed8326754d0a8f4&)

[in-game visual idea](https://cdn.discordapp.com/attachments/1164392384545702058/1168346985556889701/Elder-mace-test-visual.jpg?ex=65516eec&is=653ef9ec&hm=a0504871d30453fbaafa71ab363bd06f72c4b9dcfec3b35aaeae017f5d88e9fa&)

**Comment by MidnightsFX** [comment]
This is out in 1.5.7!
