### ISSUE TITLE
Minor visual and balance critique

### ISSUE THREAD

**Issue by SuperMegaBuffet** [MidnightsFX/Valheim_Armory#2]
Mod is great, seems to be running as intended. Two comments, the serpent buckler is very large for a buckler, model could be reduced maybe 50% in size, and the surtling core arrows could be x20 per crafting rather than x50, or this could be a configurable option for all new arrows. Again, awesome work.

**Comment by MidnightsFX** [comment]
Thanks for the feedback! I will look at reducing the serpent buckler size in the future, I'm moving to a new model for that shield that will make it a lot easier to work with. 

I've got a relatively large update that will allow configuration of how many arrows are crafted from the recipe for surtling arrows.

**Comment by MidnightsFX** [comment]
@SuperMegaBuffet ok 1.0.0 is out and that contains config options for how many arrows are crafted from the recipe- and defaults it to 20 instead of 50.

The shield size should be reduced a bit- tell me what yah think.

**Comment by MidnightsFX** [comment]
Marking this as closed since I haven't seen any response! Feel free to re-open or comment again if you would like to see further adjustments.
