### ISSUE TITLE
Custom Projectiles Disappear for Clients

### ISSUE THREAD

**Issue by sevenindex** [MidnightsFX/Valheim_Armory#21]
My friends and I play on a peer to peer server and we noticed that some of the projectiles from this mod weren't working. Any projectile (Bone Arrows, Staff Projectiles, Crossbow Bolts, etc) would vanish a second after being fired, but only for the clients, not the host. Projectiles can still do damage, but only at point blank range. 

I'm not sure if this is bug or we just installed something wrong, but we'd appreciate it if you could help us out. Thanks!

**Comment by MidnightsFX** [comment]
Interesting! Could I get a mod-list and potentially some BepInEx logs for this? Also what version of the game is this happening on for you?

Also if possible could you verify that the following bow projectiles do or don't work?
```
Chitin Arrow
Bone Arrow
```

BepInEx logs can be found in your BepInEx folder (which is located in your game directory or virtual directory for mod managers) in the `LogOutput.txt` file

**Comment by MidnightsFX** [comment]
I've also got a dev build that you could try out and see if it fixes some/all of those issues.

[Valheim_Armory-1.6.5-preview.zip](https://github.com/MidnightsFX/Valheim_Armory/files/13787931/Valheim_Armory-1.6.5-preview.zip)

**Comment by MidnightsFX** [comment]
This should be fixed in `1.6.5`

**Comment by sevenindex** [comment]
**We're probably gonna switch over to the developer version for now, but thanks again for helping us out. If you still want some of the info we gathered from testing it's right down here.** 

Ok so here's all the info I could gather:

### **Mod List (In Order):**
- **BepInExPack_Valheim** [denikson (v5.4.2202)]
- **SkillInjector** [pipakin (v1.1.1)]
- **MoreSkills** [MacharaStormwing (v0.2.6)]
- **DeathTweaks** [Pineapple (v1.3.0)]
- **Jotunn** [ValheimModding (v2.15.2)]
- **Clutter** [OdinPlus (v0.1.5)]
- **OdinsTraps** [OdinPlus (v1.1.12)]
- **OdinHorse** [OdinPlus (v1.2.6)]
- **OdinBear** [OdinPlus (v1.2.8)]
- **OdinsSteelWorks** [OdinPlus (v0.1.23)]
- **PlantEverything** [Advize (v1.16.2)]
- **MultiUserChest** [MSchmoecker (v0.5.6)]
- **VikingsDoSwim** [blacks7ar (v1.3.1)]
- **WieldEquipmentWhileSwimming** [blacks7ar (v1.0.8)]
- **ValheimArmory** [_You!_ (v1.6.4)]

### **Projectile Testing:**
**Default Version:**
Only the _Blackmetal_, _Surtling Fire_ and _Chitin Arrows_ didn't disappear after firing. _The Drudic Staffs of Fire and Ice_ also didn't vanish, but we're pretty sure that because they use existing projectiles. Otherwise every other projectile disappears after about a second of flight time. (Arrows, Crossbow Bolts and Magic Projectiles)

**Developer Version:**
The only projectiles that vanished were _every Crossbow Bolt_. Although this was hard to notice since the bolt travels so fast, so it doesn't have a big impact on gameplay.
