### ISSUE TITLE
Moder Spear issue

### ISSUE THREAD

**Issue by HandyHanderson** [MidnightsFX/Valheim_Armory#25]
Position in hand of Moder Spear is skewed. Below comparison.
Fang Spear:
![image](https://github.com/MidnightsFX/Valheim_Armory/assets/172886119/5cdbedaa-4589-4d92-89c3-68add0f13d22)
Moder Spear:
![image](https://github.com/MidnightsFX/Valheim_Armory/assets/172886119/32a601bd-2a7f-45f7-a1d1-8e97e61fa814)

**Comment by MidnightsFX** [comment]
Hey! I'll get this fixed next update

**Comment by MidnightsFX** [comment]
Feel free to mention if you don't feel the changes fixed this enough- otherwise I will close this in a day or so.

**Comment by HandyHanderson** [comment]
Yep. A lot better now.
![image](https://github.com/MidnightsFX/Valheim_Armory/assets/172886119/96019ac0-032c-4f62-a749-6641710ea62a)
Thanks! 😁
