### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Iterny** [MidnightsFX/Valheim_Armory#27]
omg i'm so sorry to disturb becuase of such small thing, but i made hilarious typo:

"item_bolt_fire": "Онгенный болт"

should be 

"item_bolt_fire": "Огненный болт"

funny thing that i have typo in this exact item last time and changed it to another typo XDD
i'm so sorry

**Comment by Iterny** [comment]
don't update mod instanly because of that, just change it if possible for next big update

**Comment by MidnightsFX** [comment]
No worries I'll get that updated and wait to push till next content release.

**Comment by MidnightsFX** [comment]
This will be fixed in 1.15.2
