### ISSUE TITLE
Blood Bone Battlepick handle

### ISSUE THREAD

**Issue by HandyHanderson** [MidnightsFX/Valheim_Armory#28]
Handle of the Blood Pick is a little too thick, making it clip over the hand when held, compared to other picks.

![image](https://github.com/user-attachments/assets/908380da-19bd-4384-b416-b6a9e1bcb2ba)
![image](https://github.com/user-attachments/assets/d4fd216d-ce01-4933-8e1e-3dae8ebe34f2)
![image](https://github.com/user-attachments/assets/30e3b1e1-254b-46ed-a9ff-55b78b92e9cc)
![image](https://github.com/user-attachments/assets/ee759a0c-627d-4e00-921f-5be5b4f909d3)

**Comment by MidnightsFX** [comment]
I'll take a look at this, it looks like I need to make the handle a little smaller and move the model downwards.

Whatever fix ends up happening it will be included in the next update.

So far, it looks like I might need to redo more than just manipulate the model a little for this, regardless it will be in the next update.

**Comment by MidnightsFX** [comment]
This is fixed in the 1.16.0 preview build and will be released when that is.
