### ISSUE TITLE
RU localization for 1.16.0

### ISSUE THREAD

**Issue by Iterny** [MidnightsFX/Valheim_Armory#29]
Hello, translated new weapons for upcoming mod update:

item_bronze_sledge: "Бронзовая кувалда"
item_bronze_sledge_description: "Внушительный камень, закрепленный бронзовыми вставками и ремнями из шкур троллей."

item_moder_greatsword: "Промерзший клеймор"
item_moder_greatsword_description: "Огромный меч, выкованный в вечных льдах и усиленный скорбью Матери."

**Comment by MidnightsFX** [comment]
Thank you! I've included those in the translations, and they will be part of the 1.16.0 update!
