### ISSUE TITLE
More Config Options Please

### ISSUE THREAD

**Issue by Mliekseter** [MidnightsFX/Valheim_Armory#3]
Great mod, finally some uses for all that chitin I had lying around. Some more config options would be fantastic, like being able to change the crafting table used for things or changing the block armour, etc, values on things. For example like the config options in GapFiller (https://valheim.thunderstore.io/package/Smoothbrain/GapFiller/) or BowPlugin (https://valheim.thunderstore.io/package/blacks7ar/BowPlugin/).

**Comment by MidnightsFX** [comment]
Good callouts! I'll work on exposing more of those.

I have an update coming out which should make it a lot easier to for those to be configured.

Which crafting table are you interested in having change? The crossbow from the artisan table?

**Comment by MidnightsFX** [comment]
Block amount is exposed in the 1.0.0 release. I'm still looking at a handful of other configurable variables to expose. Is there anything specific that you are interested in?

**Comment by Mliekseter** [comment]
My specific idea was to move the bronze crossbow to the forge rather than the artisan table. I've currently got a flint crossbow from another mod, so I wanted to use the bronze one as an midpoint between the flint crossbow and the arbalest, so I wanted to adjust it to be somewhere in the iron tier. Some similar mods have config options for setting what level of crafting table is needed for individual items, so my plan was to make it require a level 3 forge, since that requires Iron or chains to reach.

As for other config options, again I suggested it based on options I've seen in some other mods that expose almost all the stats on a weapon in the config file, including the recipe. That said, I personally only really want to change the crossbow and antlergeir; I figured something made from Eikthyrs antler should do a little bit of thunder damage. =P

**Comment by MidnightsFX** [comment]
> My specific idea was to move the bronze crossbow to the forge rather than the artisan table. I've currently got a flint crossbow from another mod, so I wanted to use the bronze one as an midpoint between the flint crossbow and the arbalest, so I wanted to adjust it to be somewhere in the iron tier. Some similar mods have config options for setting what level of crafting table is needed for individual items, so my plan was to make it require a level 3 forge, since that requires Iron or chains to reach.

Fair! in 1.0.0 I moved the bronze crossbow to the forge because the artisan table was a bit of a challenge. Because my ultimate goal with having it locked behind the artisan table was to make it a post-mountain weapon I also changed the recipe by swapping out chains for a singular dragon tear (more not needed for upgrades). So the recipe is now Finewood, Bronze, Guck and Dragontear.

The bolts are still on the artisan table as are turret bolts so I thought that made sense.


> As for other config options, again I suggested it based on options I've seen in some other mods that expose almost all the stats on a weapon in the config file, including the recipe. That said, I personally only really want to change the crossbow and antlergeir; I figured something made from Eikthyrs antler should do a little bit of thunder damage. =P

Fair! I actually added the config option to do lightning damage when I merged the 3 antler atgier models (in 1.0.0) and the final model still has occasional sparks.

I don't have the recipes exposed yet and that is on my todo list!

**Comment by MidnightsFX** [comment]
1.1.0 is out now with many more configuration options.

There are still a handful of things I plan on adding configuration wise, but all of the things requested originally here are added so I am going to close this!
