### ISSUE TITLE
Missing items localization

### ISSUE THREAD

**Issue by Iterny** [MidnightsFX/Valheim_Armory#30]
Hi, sorry, wicked goverment in my country banned discord and it's not working properly so i didn't see update changelog in time and missed these new items, so there is translation:  

  "item_mistland_mace": "Булава из черного мрамора",
  "item_mistland_mace_description": "Идеальное орудие, чтобы давить назойливых тараканов.",
  "item_sledge_flametal": "Огнеметаллическая кувалда",
  "item_sledge_flametal_description": "Громадная кувалда, идеально сбалансированная. Одновременно неподъемная и ужасающая мощь.",
  "item_sledge_flametal_lightning": "Раскат грома",
  "item_sledge_flametal_description_lightning": "Громадная кувалда, с каждым взмахом будто рвет небеса оглушительными раскатами грома.",
  "item_sledge_flametal_nature": "Дрожь земли",
  "item_sledge_flametal_description_nature": "Громадная кувалда, наполненная природной энергией. С таким оружием можно остановить целую армию недругов.",
  "item_sledge_flametal_blood": "Смертельный удар",
  "item_sledge_flametal_description_blood": "Громадная кувалда, пульсирующая зловещей энергией. Чем ожесточеннее бой, тем яростнее её удары."

**Comment by MidnightsFX** [comment]
I'll get these updated! This is for the Russian translation yeah?

**Comment by Iterny** [comment]
yup

**Comment by MidnightsFX** [comment]
This will be included in the next release!
