### ISSUE TITLE
Localization update RU

### ISSUE THREAD

**Issue by Iterny** [MidnightsFX/Valheim_Armory#32]
Hi, i'm little late with those new items: 

 "item_dual_axes_flint": "Кремневые топоры",
  "item_dual_axes_flint_description": "Два топора лучше, чем один! Да и кому вообще нужно блокировать удары?",
  "item_dual_axes_bronze": "Бронзовые топоры",
  "item_dual_axes_bronze_description": "Два лезвия - вдвойне веселее! Деревья трепещут в ужасе.",
  "item_dual_axes_iron": "Железные топоры",
  "item_dual_axes_iron_description": "Мало кто выстоит против разъяренного викинга с топором в каждой руке."

**Comment by Iterny** [comment]
As always no rush with updating

**Comment by MidnightsFX** [comment]
Will get these updated in the next release, thank you!

**Comment by Iterny** [comment]
<3
