### ISSUE TITLE
Iron Greatsword wrong materials

### ISSUE THREAD

**Issue by olavr-dev** [MidnightsFX/Valheim_Armory#4]

**Comment by olavr-dev** [comment]
I removed this issue earlier because I thought I was looking at the wrong mod.

However, I am noticing that the Iron Greatsword is unlocked with bronze instead of iron.

Takes 25 Bronze to craft instead of 25 Iron?

**Comment by MidnightsFX** [comment]
I'll get the recipe fixed! Thanks for spotting that must have copy pasta'd

**Comment by MidnightsFX** [comment]
Will have an update with the fixed recipe out later tonight

**Comment by MidnightsFX** [comment]
1.0.1 is out and has the fix for this!
