### ISSUE TITLE
VAAntler_dagger falls trought ground

### ISSUE THREAD

**Issue by BigBeatProphet** [MidnightsFX/Valheim_Armory#6]
also permanent spam of this in log
> Moved up item VAAntler_dagger(Clone)
seems like dagger falling trought ground and reapper at ground level, also there is no way to pick it up

**Comment by MidnightsFX** [comment]
Thanks for the report! I'll get that fixed in the next release.

**Comment by MidnightsFX** [comment]
This should be fixed in the now released 1.3.0
