### ISSUE TITLE
Holding Eikthyrs Crown

### ISSUE THREAD

**Issue by jimkimjat** [MidnightsFX/Valheim_Armory#7]
Character holding the great axe on the top part of the weapon instead of the handle. It was working fine before the latest update.

**Comment by MidnightsFX** [comment]
Hmm well that is not ideal! I'll see about getting an update out shortly to fix that.

**Comment by MidnightsFX** [comment]
Alrighty, small update is out 1.3.1 which fixes this. Sorry about that!
